name: $(Date:yyyyMMdd)-$(ProjectName)-$(TeamName)

trigger:
- none

variables:
- group: Azure DevOps Onboarding

jobs:
- job: Onboard
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: azure-devops-onboarding@0
    inputs:
      Action: 'onboardTeam'
      ProjectName: '$(ProjectName)'
      TeamName: '$(TeamName)'
      Description: '$(Description)'